// React/React-Example/resources/js/components/TodoItem.jsx
import React, { useContext, useState } from 'react';
import TodoContext from '../providers/TodoContext.js';

function TodoItem(props) {
    const todo = props.todo;
    const { removeTodo, completeTodo } = useContext(TodoContext);
    const [editing, setEditing] = useState(false);
    const [title, setTitle] = useState(todo.title);
    const editTodo = () => {
        setEditing(true);
        setTimeout(() => {
            const input = document.getElementById('title');
            input.focus();
        }, 1);
    };
    // since we dont have v-model, wich updates automatically, we need to update the state manually
    // we can use the events to listen to the changes, but we need to update the state manually
    const changeTodoTitle = (e) => {
        setTitle(e.target.value);
    };
    const saveTodo = () => {
        setEditing(false);
    }
    const handleKeyPress = (e) => {
        if (e.key === 'Enter') {
            saveTodo();
        }
    }
    return (
        <li>
            {/* like v-for, there isnt a v-if/v-else in react, instead, we can just ask if a variable is true
                and return a component in the case it is, and another if it is false
                if you only need a component in the true case, you can do { variable && <component/> } and
                it will only render when variable is true */}
            {!editing ? (
                <span onDoubleClick={editTodo}>{title}</span>
            ) : (
                <input id="title" type="text" onChange={changeTodoTitle} value={title} onBlur={saveTodo} onKeyUp={handleKeyPress} />
            )}
            {/* the functions called with onClick, and any other event has to be an arrow function,
                otherwise it will be called automatically */}
            <button onClick={() => completeTodo(todo.id)} >{ todo.completed ? 'Uncomplete ' : 'Complete'} todo</button>
            <button onClick={() => removeTodo(todo.id)} >Delete todo</button>
        </li>
    );
}
export default TodoItem;

// Vue/Vue-Example/resources/js/components/TodoItem.vue
<template>
    <div>
        <div>
            <!-- If we want to print out values of variables, we need to use {{}} -->
            {{todo.id}}
        </div>
        <!-- v-if only renders the element/component if the value is true -->
        <div v-if="!editing" @dblclick="editTodo">
            {{todo.title}}
        </div>
        <!-- v-else renders the element/component if the value is false -->
        <!-- you can also use v-else-if in case there are more options -->
        <input v-else ref="a" @blur="saveTodo"  @keyup.enter="saveTodo" type="text" v-model="todo.title">
        <div>
            {{todo.completed}}
        </div>
        <div>
            <button @click="toggleCompletedTodo">{{ todo.completed ? 'Uncomplete Todo' : 'Complete Todo'}}</button>
            <button @click="deleteTodo">Delete Todo</button>
        </div>
    </div>
</template>
<script>
    export default {
        name: 'TodoItem.vue',
        props: ['todo'],
        data(){
            return {
                editing: false,
            }
        },
        methods: {
            toggleCompletedTodo() {
                this.todo.completed = !this.todo.completed;
            },
            deleteTodo() {
                this.$emit('deleteTodo', this.todo);
            },
            editTodo() {
                this.editing=true;
                setTimeout(() => {
                    this.$refs.a.focus();
                }, 10);
            },
            saveTodo() {
                this.editing=false;
            },
        },
    };
</script>
